product:
    resource:
        path: ../src/Product/Controller/
        namespace: App\Product\Controller
    type: attribute
security:
    resource:
        path: ../src/Security/Controller/
        namespace: App\Security\Controller
    type: attribute
