POST https://my-products-server.ddev.site/login
Content-Type: application/json

{
  "username": "firstUser",
  "password": "1234"
}

###

POST http://127.0.0.1:8080/login
Content-Type: application/json

{"username":"firstUse","password":"1234"}



###

GET https://my-products-server.ddev.site/me/products

###
POST https://my-products-server.ddev.site/me/product
Content-Type: application/json

{
  "gtin": 5000157024671
}

###
POST https://my-products-server.ddev.site/me/product
Content-Type: application/json

{
  "gtin": 5000157024671,
  "score": 3
}